web:
  - web/src/**/*
  - web/public/**/*
  - web/README.md

api:
  - api/src/**/*
  - api/README.md

migration:
  - api/db/**/*

test:
  - '*.test.{ts,js,tsx,jsx}'

docs:
  - any: ['README.md']

workflow:
  - all:
      [
        '!web/src/**/*',
        '!web/public/**/*',
        '!api/src/**/*',
        '!api/db/**/*',
        '!*.test.{ts,js,tsx,jsx}',
        '!README.md',
        '!web/README.md',
        '!api/README.md',
      ]
