name: Lint, Test, & Build

on:
  pull_request:
    branches:
      - development
      - master
      - 'release/**'
      
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn rw lint --fix

      - name: Test
        run: yarn rw test --no-watch

      - name: Build
        run: yarn rw build
